### ISSUE TITLE
Prepis rozhovoru so zadávateľom

### ISSUE THREAD

**Issue by silny7** [TIS2018-FMFI/visionlab-meraky#1]

**Comment by silny7** [comment]
11.10.2018 21:13 

Odoslaný dokument na schválenie zadávateľovi s prepisom záznamu z prvého stretnutia.

Po obdržaní odpovede bude táto issue zatvorená.

[Prepis rozhovoru so zadávateľom.pdf](https://github.com/TIS2018-FMFI/visionlab-meraky/files/2470358/Prepis.rozhovoru.so.zadavatelom.pdf)

**Comment by silny7** [comment]
Odpoveď od zadávateľa v celom nezmenenom rozsahu:

> Dobry den,
vdaka za zaznam zo stretnutia,je v poriadku. Praca s grafmi sa tyka kinematickej skupiny, bola v zadani, ale moj nazor je taky ze lepsie bude sa sustredit na cast rozpoznavania, grafy v tomto pripade nedavaju velky zmysel.
S pozdravom
Peter Varga


Issue uzatváram.

**Comment by pavelpetrovic** [comment]
tak teraz dokladne treba zvazit ako na to zareagujete, ci vypustate grafy celkom alebo nie. je to na vas. ale katalog poziadaviek treba aby zodpovedal vyslednemu rozhodnutiu.
