### ISSUE TITLE
Katalóg požiadaviek - finálna fáza

### ISSUE THREAD

**Issue by Ferious** [TIS2018-FMFI/visionlab-meraky#10]
Máme tu ešte pár vecí na prerobenie, bol by som rád keby sa natom popracovalo a pridali by ste vaše stanovisko k týmto otázkam aj vy ostatné veci som už odladil: 
"do KP treba nutne uviest CO NAJVIAC prikladov = OBRAZKOV, ktore
bude system vediet spracovat!!! - pisal som uz mail kam by sme to mali presne dat do kp"

>>> --------------------------------------------------------------------------------------------------
  - kedy človek môže nastaviť optimálny jas a kontrast:  nie je jasne
aky je vztah medzi prahom a jasom/kontastom. treba sa vyjadrit PRESNE!

  - číslice z meracích zariadení, ale aj desatinné čísla => akym
sposobom urci desatinnu bodku (moze byt zle viditelna, alebo tam ani
nemusi byt, ked je cela cast od desatinnej oddelena nejakymi
okienkami)?

  - ako sa bude prevadzat uhlova poloha rucicky na konkretne cisla?
Bude system vari schopny precitat nejake rozne ocajchovania poloh
rucicky na ciferniku?? alebo si to nejak nastavi pouzivatel? ako?
kedy? kde?

[Katalog poziadaviek.docx](https://github.com/TIS2018-FMFI/visionlab-meraky/files/2518957/Katalog.poziadaviek.docx)

**Comment by silny7** [comment]
K druhému bodu:
Pozíciu desatinných čísiel zadá používateľ. Teda systém nebude musieť rozoznávať desatinnú čiarku alebo iný spôsob oddelenia desatinnej časti od celého čísla.

**Comment by silny7** [comment]
**6.11.2018 odpoveď od cvičiaceho**

> dakujem za aktualizaciu KP.
> tu su moje drobne pripomienky:
> 
> "Pojmy, ktoré by mohli byť pre čitateľa tohto dokumentu nezrozumiteľné:"
> 
> - vasou ulohou nie je starat sa do citatela. citatel sa stara o seba sam.
> chceli ste tam napisat, ze v tej casti definujete pojmy, s ktorymi dokument
> dalej pracuje v nasledujucich castiach a je potrebne ich vyznam upresnit.
> 
> iteragovať => interagovat  - ale v tej vete mate dve slovesa, vyberte
> si len jedno, inak veta nema zmysel
> 
> 3.1.1. "poprípade štvorec" vyskrtnut
> 
> nie je mi jasne:
> 
> - system sam uhadne, ci sa v tej-ktorej oblasti budu vyskytovat
> rucickove alebo digitalne udaje, alebo to bude nastavovat pouzivatel?
> 
> 3.1.9. zadáme kde sa nachádza začiatočná hodnota a kde sa bude
> nachádzať koncová hodnota
> => ako to zadame?
> 
> rucickova vzdialenost - tento termin ste v slovniku pojmov
> nedefinovali a nie je to vseobecne znamy pojem
> 
> bude system vediet cislice vo vyznacenej oblasti hladat automaticky,
> alebo mu bude treba pomoct presnejsie stanovit, kde sa jednotlive
> cislice nacitavaneho digitalneho cisla vyskytuju?
> 
> je tam stale mnozstvo dalsich nedostatkov.
> 
> napr. moze pouzivatel urcit do akeho suboru sa vystup uklada? ako sa
> prepina medzi konfiguraciami? bude mozne jednotlive oznacene oblasti
> nejak pomenovat, alebo to bude len prva, druha, ...? a pouzivatel
> poriadne nebude vediet, co je co vo vystupnom subore? prahove hodnoty
> sa budu nastavovat pre kazdu oblast zvlast? moze byt jedna oblast
> automaticka a druha rucne zadana? viacere poziadavky su kombinovane a
> treba ich rozbit na atomicke poziadavky, vopred nastaveny casovy
> interval sa len raz okrajovo spomenie  v 3.1.3 ale nie je jasne ako sa
> nastavuje a kedy a pod.
> takych veci bude este asi viac, ale musite to spravit tak, aby som tam
> uz ziadnu takuto medzeru nenasiel, takze opat, ked to upravite mi to
> este treba poslat na kontrolu.

**Moje návrhy na úpravu:**

_3.1.1_ Systém sám neuhádne, či sa jedná o analogový alebo digitálny merák. Užívateľ pri vytvorení ROI vyberie typ meracieho prístroja, o aký sa jedná.

_3.1.9_ S týmto neviem. To by možno vedel povedať @tamaskabai , ktorý už skúša prácu v OpenCV a teda by možno vedel povedať, ako toto riešiť.

**Ďalšie odpovede:**
- Áno, používateľ bude môcť určiť súbor, do ktorého sa výstup ukladá
- Konfigurácia sa bude dať zmeniť pomocou LOAD buttonu - to už je ale o GUI, ktorá bude popísaná v Návrhu. Jednoducho konfigurácie sa budú dať vybrať a načítať z priečinka.
- Jednotlivé ROI budú iba jedna, druhá atď. Každá ale bude mať svoju jednotku, v ktorej sa hodnota meria a teda výstupný súbor bude formátovaný tak, aby bolo zrozumiteľné, čo sa odmeralo.
- K prahovaniu neviem osobne povedať ja nič.

@Ferious @zrubec6 @tamaskabai
 Pridajte svoje návrhy, zapracujú sa do KP a bude znovu poslaný na kontrolu. Vďaka.

**Comment by Ferious** [comment]
Moje návrhy:

3.1.3 pridať k tomuto bodu ->
Viac o časovom intervale odčítavania v bode 3.1.7

3.1.7 pridať k tomuto bodu ->
Časový interval odčítavania používateľ zadá do GUI, kde bude políčko s názvom frekvencia odčítavania, ktorý treba zadať pred spustením programu.

**Comment by silny7** [comment]
Posledná verzia (12.11.2018). Dnes odoslaná na schválenie zadávateľovi.


[Katalóg-požiadaviek.docx](https://github.com/TIS2018-FMFI/visionlab-meraky/files/2572532/Katalog-poziadaviek.docx)
[Katalóg-požiadaviek.pdf](https://github.com/TIS2018-FMFI/visionlab-meraky/files/2572533/Katalog-poziadaviek.pdf)

**Comment by silny7** [comment]
Odpoveď a pripomienky zadávateľa.

> Dobry den,
> 
>  
> 
> vdaka za zaslanie dokumentu. Iba jedna pripomienka
> 
>  
> 
> 3.1.3.3 Spracovanie odčítaných hodnôt
> 
> Systém z nameraných hodnôt vypočíta priemer (za predchádzajúcich 60 sekúnd) a takisto aj medián (za predchádzajúcich 60 sekúnd). Tieto hodnoty budú zaznamenané aj v súbore s výstupnými dátami.
> 
>  
> 
> Hodnotu 60 sekund pre pocitanie priemeru alebo medianu by davalo zmysel nastavovat. Kedze uzivatel si vie podla 3.1.7 Nastavenie frekvencie odčítavania, nastavit frekvenciu, v tomto okne by mohlo byt aj priemerovanie a median.
> 
> Inak je dokument formalne v poriadku a navrhujem aby ste pokracovali navrhom riesenia.
> 
>  
> 
> S pozdravom
> 
> Peter Varga

Pripomienky boli zapracované. Pripájam teda finálnu verziu katalógu požiadaviek a čoskoro bude táto issue uzatvorená. Takisto pripájam katalóg požiadaviek do branch-u Projektová dokumentácia.

[Katalóg-požiadaviek.docx](https://github.com/TIS2018-FMFI/visionlab-meraky/files/2572802/Katalog-poziadaviek.docx)
[Katalóg-požiadaviek.pdf](https://github.com/TIS2018-FMFI/visionlab-meraky/files/2572803/Katalog-poziadaviek.pdf)

**Comment by silny7** [comment]
Menšie úpravy. Issue uzatváram
[Katalog-poziadaviek.docx](https://github.com/TIS2018-FMFI/visionlab-meraky/files/2585388/Katalog-poziadaviek.docx)
[Katalog-poziadaviek.pdf](https://github.com/TIS2018-FMFI/visionlab-meraky/files/2585389/Katalog-poziadaviek.pdf)
