### ISSUE TITLE
Špecifikácia vonkajších interfejsov a nastavenie kamery

### ISSUE THREAD

**Issue by silny7** [TIS2018-FMFI/visionlab-meraky#14]
vonkajšie zariadenia, s ktorými bude systém pracovať (kamera, súbory)

súbory sa riešia v samostatných issues

**Comment by zrubec6** [comment]
* V prípade, že systém bude odčítavať hodnoty pomocou kamery:
     -
     - návod na nastavenie kamery v C++:  
              https://www.linkedin.com/pulse/fun-opencv-video-frames-arun-das 
     - frekvencia robenia snímok, atď 

* V prípade, že systém bude odčítavať údaje z videa:
    - 
    - *pravdepodobne len pre vývojárov systému na testovanie*
    - návod na vkladanie videa do aplikácie v C++:
            https://www.learnopencv.com/read-write-and-display-a-video-using-opencv-cpp-python/

* Systém bude pracovať so súbormi:
    - 
    * **Budeme mať dva typy súborov:**
         - Vstupný súbor (config file):
              - bude obsahovať údaje o konfigurácii
              - z posledného vytvoreného systém načíta poslednú konfiguráciu (pre ROI, interval ukladania, atď)
              - opis tohto súboru je možné nájsť tu: 
                             https://github.com/TIS2018-FMFI/visionlab-meraky/issues/12
         - Výstupný súbor:
              - bude obsahovať namerané hodnoty
              - formát a opis tohto súboru je možné nájsť tu: 
                             https://github.com/TIS2018-FMFI/visionlab-meraky/issues/13

**Comment by zrubec6** [comment]
### Nastavenie kamery
 
- **Návod na nastavenie jasu a kontrastu pomocou OCV v C++:** 
https://docs.opencv.org/3.4/d3/dc1/tutorial_basic_linear_transform.html
- **_Návod na kalibráciu kamery pomocou OCV v C++ (ak bude treba):_**
https://docs.opencv.org/3.4/d4/d94/tutorial_camera_calibration.html
- **Jednoduchý návod na prahovanie obrázka pomocu OCV v C++:**
https://docs.opencv.org/3.4.3/db/d8e/tutorial_threshold.html
  * _Prahovania a ich implementácia:_
https://www.youtube.com/watch?v=UAi7rIF00LA
