### ISSUE TITLE
UML component diagram

### ISSUE THREAD

**Issue by Ferious** [TIS2018-FMFI/visionlab-meraky#15]
Prvá verzia UML component diagramu

https://drive.google.com/file/d/1YMX7sbZv__bO6zG0ivDlJcimjFKk4yRc/view?usp=sharing

**Comment by pavelpetrovic** [comment]
vedeli by ste ku vsetkym interakciam medzi modulmi (teda ich vzajomnym interfejsom) definovat, ako vyzeraju? ktory modul od ktoreho modulu kedy co pozaduje/dostava/informuje ho/...?

**Comment by Ferious** [comment]
Pripájam upravenú verziu component diagramu

https://drive.google.com/file/d/1V7ScfdPYmYRkyky-OBOnfORuFwrvO2XT/view?usp=sharing

**Comment by zrubec6** [comment]
Nachádza sa v návhru.
