### ISSUE TITLE
Písanie dokumentu Návrh

### ISSUE THREAD

**Issue by Ferious** [TIS2018-FMFI/visionlab-meraky#16]
Pripínam šablónu návrhu 

[Navrh.docx](https://github.com/TIS2018-FMFI/visionlab-meraky/files/2568693/Navrh.docx)

**Comment by Ferious** [comment]
[Navrh.docx](https://github.com/TIS2018-FMFI/visionlab-meraky/files/2607652/Navrh.docx)

**Comment by silny7** [comment]
Návrh doplnený o formáty vstupných a výstupných súborov

[Navrh.docx](https://github.com/TIS2018-FMFI/visionlab-meraky/files/2625495/Navrh.docx)

**Comment by zrubec6** [comment]
Návrh doplnený o Špecifikáciu vonkajších interfejsov - Kamera
[Navrh.docx](https://github.com/TIS2018-FMFI/visionlab-meraky/files/2626525/Navrh.docx)

**Comment by Ferious** [comment]
Návrh doplnený o Používateľské rozhranie
[Navrh.docx](https://github.com/TIS2018-FMFI/visionlab-meraky/files/2627048/Navrh.docx)

**Comment by tamaskabai** [comment]
Návrh doplnený o Technológie rozpoznávanie hodnôt.

Použitné technológie ešte doplním počas dňa.

[Navrh.docx](https://github.com/TIS2018-FMFI/visionlab-meraky/files/2627702/Navrh.docx)

**Comment by pavelpetrovic** [comment]
tu su moje postrehy z dnesneho stretnutia

zapisnice a issues su stale pekne
pozerame si skoro hotovy navrh
do popisu suborov uviest aj podrobny popis jednotlivych poloziek
format bodov pre analogovy typ z ukazky nie je jednoznacny
nastavenie kamery - nieco ine je v konfigu a nieco ine v navrhu gui - zladit
gui - konfiguracia - vyber automaticke / rucne - nerozumiem


sipky na prepinanie medzi ROI - budu mat text obidvoma smermi?

vyber suborov - nerozumiem
mozno: editbox s menom suboru (cela cesta) + button na fileopendialog

bude tlacidlo odstran mat aj potvrdenie?

namerana hodnota - tento string je zbytocne opakovat

- namiesto toho cosi ako tabulka s nepohyblivou hlavickou a pripadne so scrollbarom

lokalizacia LCD - huhu?

prahovanie - v gui by mala byt moznost pri rucnom prahovani zadat prahovu hodnotu
 - ci uz do editboxu, alebo nejakym posuvnikom nastavit, ale pri nastavovani by
   pouzivatel mal vidiet preview prahovania

 - asi by sa hodne hodilo mat 2 prahovacie hodnoty:
    minimalna hodnota
    maximalna hodnota
   pozitivneho sampla

pri analgoovom GUI pridat este aj minimalnu hodnotu na meraku - pre kliknuty bod
a maximalnu hodnotu na meraku pre kliknuty max. bod
MINVAL,MAXVAL


0. vystrihnutie ROI podla zadanych suradnic 
1. prahovanie
2. dilatacia - aby sa spojili segmenty, ktore su mozno rozpojene
   tym kazda cislica bude suvisly segment
3. segmentacia - pohladanie suvislych utvarov v obraze
4. odfiltrovat segmenty, ktore su prilis male (treba mat zasa nejaku limitnu hodnotu - idealne v konfigu)
5. bounding box pre kazdy jeden segment
6. dostavame segmenty v ktorych maju byt cislice (v roznej skale) - v nich vyratame kolko pixlov na ocakavanych miestach svieti (ak je aspon 30% - tak svieti, inak svieti)
7. porovnat zisteny charaakteristicky retazec s predlohami:

  AAAA
 B    F
 B    F
 B    F
  CCCC
 D    G
 D    G
 D    G
  EEEE

     A B C D E F G 
  0  1 1 0 1 1 1 1
  1  0 0 0 0 0 1 1
  2  1 0 1 1 1 1 0 
  ...

8. zlepit zistene cislice do jedneho vysledneho cisla podla poradia v x-ovej suradnici
   a posunut podla poctu desatinnych miest

analogova:

 - treba mat odlozeny jeden obrazok s pozadim, voci ktoremu sa robi rozdiel
     -> mal by vzniknut kombinaciou troch obrazkov, ked je rucicka na roznom mieste
        O1, O2, O3
                PozObr = pozriem na pixel vo vsetkych troch obrazkoch a ten, ktory sa najviac lisi
                                nepouzijem, ostanu mi dva a z nich urobim priemer
                               takto prejdem vsetky pixle v troch obrazkoch
                               - v GUI by malo byt tlacidlo, ktorym sa tieto tri obrazky daju do systemu "odfotit"

 - z troch bodov treba mat vypocitany stred otacania rucicky:
    mate dve tetivy MIN,X,MAX
     tetiva MIN,X - jej os  -> p1
     tetiva X,MAX - jej os  -> p2
    najdete priesecnik priamok p1, p2  -> [SX,SY]
 - vypocitat celkovy uhol medzi MIN A MAX   MIN-[SX,SY]-MAX
    ALFAMAX


1. vystrihnutie ROI 
2. odcitanie od pozadoveho obrazka (s urcitou toleranciou, pretoze kamera mierne sumi)
   => vysledok by mala byt rucicka 
       -> zo vsetkych bodov rucicky najdete tie, ktore su najdalej od stredu rucicky [SX,SY]
       -> ten povazujeme za "hrot rucicky"
   -> vypocet uhla medzi 
        ALFA = MIN-[SX,SY]-[HX,HY] 
   -> aktualna hodnota
        VAL = MINVAL + (MAXVAL - MINVAL) / ALFAMAX * ALFA


prediskutovali sme navrh, prosim vytvorit kompletnu verziu navrhu
a zaroven priebezne testovat algoritmy

rozdelit pracu medzi clenov na implementacii
a potom sa toho pokusit drzat

**Comment by silny7** [comment]
**UPDATE**

Opravenie config_file formátu aby sedel s konfiguráciou systému.
Doplnenie popisu ku formátu konfiguračného súboru.
Upravenie bodu 2.1. aby sedel s konfiguráciou a konfiguračným súborom.
[Navrh.docx](https://github.com/TIS2018-FMFI/visionlab-meraky/files/2629414/Navrh.docx)

**Comment by zrubec6** [comment]
**UPDATE**
Návrh doplnený o UML State Diagram a jeho opis.
[Navrh.docx](https://github.com/TIS2018-FMFI/visionlab-meraky/files/2650837/Navrh.docx)

**Comment by Ferious** [comment]
**UPDATE**
Návrh bod 4.upravený - Používateľské rozhranie
[Navrh.docx](https://github.com/TIS2018-FMFI/visionlab-meraky/files/2651117/Navrh.docx)

**Comment by tamaskabai** [comment]
**UPDATE**
Návrh bod 5.1. doplnený a bod 6. upravený (6.2 nie je 100%)

[Navrh.docx](https://github.com/TIS2018-FMFI/visionlab-meraky/files/2652750/Navrh.docx)

**Comment by silny7** [comment]
[Navrh.docx](https://github.com/TIS2018-FMFI/visionlab-meraky/files/2663527/Navrh.docx)

**UPDATE 10.12.2018**
* Menšie korekcie v texte
* Odstránenie časti rozdelenie na moduly - je to v časti o komponentnom diagrame.

**Comment by silny7** [comment]
**UPDATE 12.12.2018**

* Doplnenie triedneho diagramu

[Návrh.docx](https://github.com/TIS2018-FMFI/visionlab-meraky/files/2672775/Navrh.docx)

**Comment by silny7** [comment]
[Návrh.docx](https://github.com/TIS2018-FMFI/visionlab-meraky/files/2696093/Navrh.docx)

**UPDATE 19.12.2018**

- úprava výstupného súboru po pripomienkach od zadávateľa
- popis algoritmu odčítavania analogových prístrojov

**Comment by pavelpetrovic** [comment]
v pouzivatelskom rozhrani tam chyba to tlacidlo na nacitanie tych troch obrazkov s rucickami v roznych polohach. nemusite to nutne dokreslovat, ak to uvediete v texte.

**Comment by Ferious** [comment]
[Navrh.docx](https://github.com/TIS2018-FMFI/visionlab-meraky/files/2697068/Navrh.docx)

**UPDATE 20.12.2018**
* úprava používateľského rozhrania bod 4

**Comment by silny7** [comment]
**UPDATE 21.1.2019**

Menšia úprava formátu výstupného súboru

[Návrh.docx](https://github.com/TIS2018-FMFI/visionlab-meraky/files/2780367/Navrh.docx)

**Comment by silny7** [comment]
**UPDATE 7.2.2019**

Finálna úprava formátu vstupného súboru

[Navrh.docx](https://github.com/TIS2018-FMFI/visionlab-meraky/files/2842287/Navrh.docx)
