### ISSUE TITLE
OpenCV: Technológia rozpoznávania číslic

### ISSUE THREAD

**Issue by silny7** [TIS2018-FMFI/visionlab-meraky#17]
Issue pre @tamaskabai. Sem prosím vkladaj svoje fungujúce programy, ktoré si vytvoril na rozpoznávavnie číslic.

**Comment by tamaskabai** [comment]
https://www.pyimagesearch.com/2017/02/13/recognizing-digits-with-opencv-and-python/

Webová stránka, kde som našiel funkcie. Program ešte nefunguje
