### ISSUE TITLE
UML Class diagram

### ISSUE THREAD

**Issue by silny7** [TIS2018-FMFI/visionlab-meraky#21]
Všetci sa pokúsime vytvoriť class diagram a vyberieme/skombinujeme do najlepšieho :) 

@Ferious @zrubec6 @tamaskabai

Deadline: do štvrtkového stretnutia, ideálne streda do polnoci!

**Comment by silny7** [comment]
Moja verzia UML Class diagramu: [TU](https://www.lucidchart.com/invitations/accept/ff3fd5a4-e414-45ad-b20b-faef63a74f99)

**Popis:**
Základnou triedou bude podľa všetkého GraphicalUserInterface. Triedy Config, Camera, ROI budú s touto triedou pracovať priamo:
- trieda Camera sa bude starať o zobrazovanie záznamu
- trieda ROI v sebe uchováva údaje o jednej oblasti záujmu
- trieda CONFIG zaobstará nastavenie systému po spustení (načíta config, vytvorí ROI, ktoré si uchováva v zozname roi)
- trieda Settings bude nastavovať rôzne komponenty (podtriedy ROI Settings, CameraSettings)

ImageGetter preberá snímky z kamery a ImageProcessor ich podľa nastavenia kamery spracuje. DataGetter následne získa hodnoty z meracích zariadení. DataCollector ukladá získané dáta a vypočíta aj priemer a medián podľa užívateľovho nastavenia.
DataWriter zapisuje získané dáta z Collectora do výstupného súboru

**Comment by zrubec6** [comment]
![tis classdiagram](https://user-images.githubusercontent.com/43668902/49216868-664cfe80-f3cc-11e8-80c1-42ca8a0a1fcc.png)

**Comment by silny7** [comment]
Moja verzia [UML Class diagramu](https://www.lucidchart.com/invitations/accept/ff3fd5a4-e414-45ad-b20b-faef63a74f99)

**Popis:**
Základnou triedou bude podľa všetkého GraphicalUserInterface. Triedy Config, Camera, ROI budú s touto triedou pracovať priamo:
- trieda Camera sa bude starať o zobrazovanie záznamu
- trieda ROI v sebe uchováva údaje o jednej oblasti záujmu
- trieda CONFIG zaobstará nastavenie systému po spustení (načíta config, vytvorí ROI, ktoré si uchováva v zozname roi)
- trieda Settings bude nastavovať rôzne komponenty (podtriedy ROI Settings, CameraSettings)

ImageGetter preberá snímky z kamery a ImageProcessor ich podľa nastavenia kamery spracuje. DataGetter následne získa hodnoty z meracích zariadení. DataCollector ukladá získané dáta a vypočíta aj priemer a medián podľa užívateľovho nastavenia.
DataWriter zapisuje získané dáta z Collectora do výstupného súboru
