### ISSUE TITLE
UML State Diagram

### ISSUE THREAD

**Issue by zrubec6** [TIS2018-FMFI/visionlab-meraky#22]
![tis state diagram](https://user-images.githubusercontent.com/43668902/49217499-02c3d080-f3ce-11e8-9816-5ca4c2ad7515.png)

**Comment by pavelpetrovic** [comment]
prebiebahnie :-)

nie celkom rozumiem tomu prechodu zo stavu

prebieha odcitavanie -> odcitavanie hodnot -> zapis hodnot do suboru

nedava mi to ziadnu logiku.

**Comment by zrubec6** [comment]
[UPDATE]
Opravený UML State Diagram.
![tis state diagram](https://user-images.githubusercontent.com/43668902/49443217-2753ea00-f7cc-11e8-9a28-3c0a32c675c5.png)
