### ISSUE TITLE
Testovacie scenáre

### ISSUE THREAD

**Issue by silny7** [TIS2018-FMFI/visionlab-meraky#23]
Treba postupne vytvárať testovacie scenáre:

Vstupné súbory - chybné, správne - na ktorých sa bude testovať implementácia Configu

Postupné kroky v GUI, ktoré užívateľ musí spraviť aby sa dostal do nejakého bodu.

Prvotný nástrel dokumentu
[Testovacie scenáre.docx](https://github.com/TIS2018-FMFI/visionlab-meraky/files/2672627/Testovacie.scenare.docx)

**Comment by tamaskabai** [comment]
**Update** 

Doplnenie Modul odčítavania dát

[Testovacie.scenare.docx](https://github.com/TIS2018-FMFI/visionlab-meraky/files/2675229/Testovacie.scenare.docx)
