### ISSUE TITLE
zaverecne upratovanie

### ISSUE THREAD

**Issue by pavelpetrovic** [TIS2018-FMFI/visionlab-meraky#26]
zlucit/vymazat vsetky branche, ostane len jeden branch master

v branchi Projektova-dokumentacia urobte:

mkdir vyvojova-dokumentacia
git mv *.pdf vyvojova-dokumentacia

a potom ho mergenite do mastera

pricom vysledne pdf technicka-dokumentacia.pdf by mohlo
ostat v root priecinku v branchi master
(aktualizovana podla stavu zdrojakov na gite)

dotiahnut vsetky issues, ostane 0 otvorenych

**Comment by zrubec6** [comment]
upratane
