### ISSUE TITLE
zostava v kode

### ISSUE THREAD

**Issue by pavelpetrovic** [TIS2018-FMFI/visionlab-meraky#27]
upratat sposob "prahovania" obrazkov.

ked sa pouziva inRange() tak potom uz nie je potrebne dalej thresholdovat, pretoze
maska, ktora z toho vypadne je ekvivalentna tomu, co vypadavalo z thresholdu.

potom podla vysledku upravte prosim vysledne PDF technicka dokumentacia

**Comment by zrubec6** [comment]
vyriešené
