### ISSUE TITLE
Vyskúšanie si Visual C++ MFC

### ISSUE THREAD

**Issue by zrubec6** [TIS2018-FMFI/visionlab-meraky#4]
Ľahký návod na spustenie: https://www.youtube.com/watch?v=jhx5kJG4GB8
Tak isto aj tu: https://msdn.microsoft.com/en-us/library/9es9d1k4.aspx
Je to dosť podobné prostrediu Lazarus alebo tak isto aj SharpDevelopu, s tým rozdielom, že to je v C++.
Tu je jednoduchá aplikácia vytvorená pomocou MFC (kalkulačka): https://www.youtube.com/watch?v=CgLLSi9aC4I

**Comment by pavelpetrovic** [comment]
Niektore drobnosti sa budu lisit pre MSVS 2017, ale to nevadi.
Podarilo sa to podla tychto tutorialov niekomu zopakovat?
A co OpenCV?

**Comment by silny7** [comment]
Odskúšané na MSVS 2017.
