### ISSUE TITLE
Návrh GUI

### ISSUE THREAD

**Issue by silny7** [TIS2018-FMFI/visionlab-meraky#7]
Informácie ohľadom návrhu GUI.

Na starosti to má: @silny7

**Comment by silny7** [comment]
Prvý nástrel hlavného okna GUI.

Určite nastanú zmeny, budú pridané ešte nejaké inputy, save button na uloženie konfigurácie, atď..

Čo treba dorobiť:
- vypýtať počet desatinných miest pre každý ROI
- vypýtať pre každý ROI v akých jednotkách je hodnota
- radio button na uloženie konfigu pri ukončení appky
- ...


![gui_navrh1](https://user-images.githubusercontent.com/36670369/47586699-393aa580-d961-11e8-8f37-f5220d8a6172.png)

**Comment by pavelpetrovic** [comment]
aj na tom obrazku to vidiet, ze pocet desatinnych miest moze byt rozny pre rozne oblasti.
naopak, nerozumiem, aky ma zmysel vypisovat to, co je pod obrazkom. chapal by som ak by to boli nadpisy stpcov, ktore sa objavia v prvom riadku vystupneho suboru. aj tak by sa hodila farebna legenda, lebo takto pouzivatel nevie, ktora je ktora. alebo je to nieco ine? ak sa budu oblasti definovat a rusit mysou/klavesnicou, tak mi riadok Pocet ROI pripada zbytocny.

**Comment by silny7** [comment]
**UPDATE 27.10.2018**
Nastali tieto zmeny:
- Hodnoty pravdepodobne nebudú vypisované do GUI ale iba do výstupného súboru (túto časť ešte treba podrobne prehodnotiť!)
- Používateľ nebude zadávať počet ROI.
- Pri vytvorení nového ROI vybehne okienko, kde používateľ zadá **počet desatinných miest** a **v akých jednotkách je meraná hodnota**
- V pravej časti bude checkbox/radiobutton, ktorý užívateľ označí, ak bude chcieť uložiť nastavenú konfiguráciu.

Nastavená konfigurácia bude obsahovať:
- Súradnice/pozíciu vyznačeného ROI
- bude si takisto pamätať aj nastavené hodnoty (počet desatinných miest, jednotku meranej hodnoty)

_Používateľské rozhranie po spustení, bez vyznačených ROI_
![main_beforestart](https://user-images.githubusercontent.com/36670369/47603459-7d26bc80-d9ec-11e8-91f6-cfccab2863eb.png)
_Používateľ vyznačil ROI, aplikácia si vypýta potrebné údaje, tie si zapamätá_
![main_roi_config](https://user-images.githubusercontent.com/36670369/47603460-7d26bc80-d9ec-11e8-85c8-2b404a9b8c9e.png)

**Comment by pavelpetrovic** [comment]
ja sa vobec nebranim tomu, aby sa hodnoty vypisovali do gui, len to z toho popisu vobec nebolo jasne, co sa to tam vypisuje
nie som si isty, ci prave nove okienko je idealne. 
jednotlive ROI by mohol vyberat klikanim a vpravo sa vzdy zobrazia udaje o vybratom, ktore moze aj menit (napriklad)
namiesto save config checkboxu by mozno bolo krajsie, keby mal pouzivatel moznost vytvarat "projekty" - ktore by mali svoje nastavenia aj priecinok, kam by sa exportovali udaje...
co ak ma dve sady pristrojov a raz pouziva softver s jednou sadou a inokedy s druhou sadou.

**Comment by silny7** [comment]
S tým vypisovaním hodnôt do GUI to musím trochu viac premyslieť, pretože tých hodnôt môže byť mnoho a muselo by sa poriešiť umiestňovanie jednotlivých výpisov.

Je pravda, že okienko neporiešilo celý problém, pretože ak by užívateľ potreboval jednotlivé vstupy upraviť, zrejme by sa k tomu nemal ako dostať. Preto sa inšpirujem vašim nápadom a užívateľovi sa kliknutím na ROI zjaví jeho nastavenie.

K vytváraniu jednotlivých projektov:
- Namiesto vytvárania jednotlivých projektov by sme užívateľovi mohli dať možnosť uložiť konfig pod nejakým menom a pred spustením samotnej aplikácie si systém vypýta konfiguračný súbor (všetky vytvorené budú v jednom priečinku) alebo sa bude dať spustiť bez konfigurácie.

Návrh GUI prerobím a znovu pridám sem.

**Comment by pavelpetrovic** [comment]
vdaka

**Comment by silny7** [comment]
UPDATE **28.10.2018**

Po vytvorení ROI sa vpravo objavia dve okienka, ktoré užívateľ musí vyplniť.
Ak bude ROI viac, kliknutím na hranu konkrétneho ROI (alebo kliknutím do vnútra ROI) sa objavia hodnoty patriace nakliknutému ROI, budú sa dať zmeniť.

Užívateľ bude môcť pomocou LOAD CONFIG nastaviť svoju uloženú konfiguráciu. Ak naopak nastaví novú, môže ju uložiť pomocou SAVE CONFIG.

_Aplikácia po spustení_
![page_1](https://user-images.githubusercontent.com/36670369/47621034-096ed780-daf2-11e8-9d85-8cf497b579d5.png)
_Aplikácia po vytvorení ROI_
![page_2](https://user-images.githubusercontent.com/36670369/47621035-096ed780-daf2-11e8-8a5f-f4b036b77282.png)

**TODO**
- Umožniť užívateľovi zvoliť si súbor, do ktorého budú zapisované výstupné hodnoty.

**Comment by zrubec6** [comment]
- OpenCV v MFC aplikácii:
https://youtu.be/yjorJu7rRiE
