### ISSUE TITLE
Fotografie/videozáznamy meracích zariadení

### ISSUE THREAD

**Issue by Ferious** [TIS2018-FMFI/visionlab-meraky#9]
Electro-Lab: František Tomana, Boris Silný
Dnes sme boli v Electro-Labe, aby sme doplnili katalóg požiadaviek a získali videozáznamy, z odčitovaných zariadení. Fotky nahrá Boris Silný a ja ich doplním do katalógu.

**Comment by silny7** [comment]
Obdržali sme dve webkamery, ktoré budeme využívať.

Po dohode s pánom Vdovjakom sme navštívili jeden z priestrorov Kvantu, kde mali k dispozícii meracie prístroje na statickom meracom pracovisku s názvom elektrolab.

Prikladám fotografie/videozáznamy meracích prístrojov a informácie o samotnom pracovisku elektrolabe.

[pic1 - digitálny](https://user-images.githubusercontent.com/36670369/47560254-04eec700-d918-11e8-9634-2bd8c27b8d60.jpg)
[pic2 - analogový](https://user-images.githubusercontent.com/36670369/47560255-05875d80-d918-11e8-9a72-d663a1b8f3eb.jpg)
[pic3 - analogový](https://user-images.githubusercontent.com/36670369/47560256-05875d80-d918-11e8-9523-b1989665c37b.jpg)
[pic4 - digitálny](https://user-images.githubusercontent.com/36670369/47560257-05875d80-d918-11e8-878a-f854d5d6b796.jpg)

**Videozáznamy:** 
[GOOGLE DISK ](https://drive.google.com/open?id=1hYs27NtetiEF6ivhF-_tNws7Ps2zANA6)

Informácie o samotnom statickom meracom pracovisku (pre potreby katalógu požiadaviek)
[letak_predna_strana_mail.pdf](https://github.com/TIS2018-FMFI/visionlab-meraky/files/2518803/letak_predna_strana_mail.pdf)
[letak_zadna_strana.pdf](https://github.com/TIS2018-FMFI/visionlab-meraky/files/2518804/letak_zadna_strana.pdf)

**Comment by pavelpetrovic** [comment]
len takapoznamka pomimo: je tam dost vela reflexov, asi by sa hodil polarizacny filter
